schema_version: 1

context:
  version: "2.90.0"

package:
  name: glib
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/glib/2.90/glib-2.90.0.tar.xz
  sha256: 17d15cac2af80a33271127408e0abc2748eb297c595c2a26409e81e14e7d1b8f

build:
  number: 0
  string: h${{ hash }}_${{ build_number }}
  script:
    file: build.sh

requirements:
  build:
    - gcc ==16.2.0
    - binutils >=2.46,<3
    - sysroot_linux-64 ==2.28
    - meson >=1.4,<2
    - ninja >=1.8,<2
    - pkgconf
  host:
    - libffi >=3.8,<4
    - pcre2 >=10.49,<11
    - zlib >=1.3,<2
    - python ==3.14.8
  run:
    - python ==3.14.8
  run_exports:
    strong:
      - glib >=2.90.0,<3

tests:
  - script:
      - bash tests/smoke.sh
    files:
      recipe:
        - tests/
    requirements:
      run:
        - gcc ==16.2.0
        - pkgconf

about:
  homepage: https://docs.gtk.org/glib/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: GLib GObject and GIO core application libraries
